<?php

/**
 * BaseMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $user
 * @property string $name
 * @property string $surname
 * @property string $address
 * @property string $category
 * @property string $description
 * @property boolean $is_partner
 * @property string $alt_image
 * @property integer $enumeration_id
 * @property Enumeration $Enumeration
 * @property Doctrine_Collection $MemberProject
 * @property Doctrine_Collection $Contact
 * 
 * @method string              getUser()           Returns the current record's "user" value
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getSurname()        Returns the current record's "surname" value
 * @method string              getAddress()        Returns the current record's "address" value
 * @method string              getCategory()       Returns the current record's "category" value
 * @method string              getDescription()    Returns the current record's "description" value
 * @method boolean             getIsPartner()      Returns the current record's "is_partner" value
 * @method string              getAltImage()       Returns the current record's "alt_image" value
 * @method integer             getEnumerationId()  Returns the current record's "enumeration_id" value
 * @method Enumeration         getEnumeration()    Returns the current record's "Enumeration" value
 * @method Doctrine_Collection getMemberProject()  Returns the current record's "MemberProject" collection
 * @method Doctrine_Collection getContact()        Returns the current record's "Contact" collection
 * @method Member              setUser()           Sets the current record's "user" value
 * @method Member              setName()           Sets the current record's "name" value
 * @method Member              setSurname()        Sets the current record's "surname" value
 * @method Member              setAddress()        Sets the current record's "address" value
 * @method Member              setCategory()       Sets the current record's "category" value
 * @method Member              setDescription()    Sets the current record's "description" value
 * @method Member              setIsPartner()      Sets the current record's "is_partner" value
 * @method Member              setAltImage()       Sets the current record's "alt_image" value
 * @method Member              setEnumerationId()  Sets the current record's "enumeration_id" value
 * @method Member              setEnumeration()    Sets the current record's "Enumeration" value
 * @method Member              setMemberProject()  Sets the current record's "MemberProject" collection
 * @method Member              setContact()        Sets the current record's "Contact" collection
 * 
 * @package    fluxweb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMember extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('member');
        $this->hasColumn('user', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('surname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('category', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('is_partner', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('alt_image', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('enumeration_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Enumeration', array(
             'local' => 'enumeration_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('MemberProject', array(
             'local' => 'id',
             'foreign' => 'member_id'));

        $this->hasMany('Contact', array(
             'local' => 'id',
             'foreign' => 'member_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'surname',
              2 => 'address',
              3 => 'category',
              4 => 'description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}