<?php

/**
 * BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $member_id
 * @property integer $enumeration_id
 * @property string $kind
 * @property string $target
 * @property Member $Member
 * @property Enumeration $Enumeration
 * 
 * @method integer     getMemberId()       Returns the current record's "member_id" value
 * @method integer     getEnumerationId()  Returns the current record's "enumeration_id" value
 * @method string      getKind()           Returns the current record's "kind" value
 * @method string      getTarget()         Returns the current record's "target" value
 * @method Member      getMember()         Returns the current record's "Member" value
 * @method Enumeration getEnumeration()    Returns the current record's "Enumeration" value
 * @method Contact     setMemberId()       Sets the current record's "member_id" value
 * @method Contact     setEnumerationId()  Sets the current record's "enumeration_id" value
 * @method Contact     setKind()           Sets the current record's "kind" value
 * @method Contact     setTarget()         Sets the current record's "target" value
 * @method Contact     setMember()         Sets the current record's "Member" value
 * @method Contact     setEnumeration()    Sets the current record's "Enumeration" value
 * 
 * @package    fluxweb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact');
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('enumeration_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('kind', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('target', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Enumeration', array(
             'local' => 'enumeration_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}