<?php

/**
 * BaseEnumeration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $position
 * @property boolean $is_active
 * @property Doctrine_Collection $Enumerations
 * 
 * @method integer             getPosition()     Returns the current record's "position" value
 * @method boolean             getIsActive()     Returns the current record's "is_active" value
 * @method Doctrine_Collection getEnumerations() Returns the current record's "Enumerations" collection
 * @method Enumeration         setPosition()     Sets the current record's "position" value
 * @method Enumeration         setIsActive()     Sets the current record's "is_active" value
 * @method Enumeration         setEnumerations() Sets the current record's "Enumerations" collection
 * 
 * @package    fluxweb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEnumeration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('enumeration');
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Project as Enumerations', array(
             'local' => 'id',
             'foreign' => 'enumeration_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}