<?php

/**
 * MemberProjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MemberProjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MemberProjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MemberProject');
    }
}