<?php

/**
 * Project
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    fluxweb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Project extends BaseProject
{
	
	public function getPosition()
	{
		return $this->Enumeration->getPosition();
	}
	
	public function getActive()
	{
		if ($this->Enumeration->getIsActive()) return 'Yes'; else return 'No';
	}
	
}
