<?php

/**
 * UnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Unit');
    }
    
    /**
     * Obtiene la instancia Unit de la homepage
     */
    public static function getHomepage()
    {
    	$results = self::getInstance()->createQuery('q')->where('q.name = ?', 'Homepage')->limit(1)->execute();
    	if (count($results) == 1) return $results[0];
    	return null;
    }
    
}